name: Deploy Eureka to MiniPC

on:
  push:
    paths:
      - '2joping-eureka/**'
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Eureka
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file 2joping-eureka/pom.xml

      - name: Deploy via SSH to MiniPC
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MINIPC_HOST }}
          username: ${{ secrets.MINIPC_USER }}
          key: ${{ secrets.MINIPC_SSH_KEY }}
          script: |
            docker stop eureka || true
            docker rm eureka || true
            docker rmi eureka:latest || true
            mkdir -p ~/ejoping/deploy/eureka
            rm -rf ~/ejoping/deploy/eureka/*
            cp ~/some-path/2joping-eureka/target/*.jar ~/ejoping/deploy/eureka/app.jar
            docker run -d \
            --name eureka \
            --memory="500m" \
            -v ~/ejoping/deploy/eureka:/app \
            -w /app \
            openjdk:21 \
            java -jar app.jar