name: Deploy Front to MiniPC

on:
  push:
    paths:
      - '2joping-front/**'
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Front
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file 2joping-front/pom.xml

      - name: Deploy via SSH to MiniPC
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MINIPC_HOST }}
          username: ${{ secrets.MINIPC_USER }}
          key: ${{ secrets.MINIPC_SSH_KEY }}
          script: |
            docker stop front || true
            docker rm front || true
            docker rmi front:latest || true
            mkdir -p ~/ejoping/deploy/front
            rm -rf ~/ejoping/deploy/front/*
            cp ~/some-path/2joping-front/target/*.jar ~/ejoping/deploy/front/app.jar
            docker run -d \
            --name front \
            --memory="500m" \
            -v ~/ejoping/deploy/front:/app \
            -w /app \
            openjdk:21 \
            java -jar app.jar