name: Deploy User-auth to MiniPC

on:
  push:
    paths:
      - '2joping-user-auth/**'
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy User-auth
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file 2joping-user-auth/pom.xml

      - name: Deploy via SSH to MiniPC
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MINIPC_HOST }}
          username: ${{ secrets.MINIPC_USER }}
          key: ${{ secrets.MINIPC_SSH_KEY }}
          script: |
            docker stop user-auth || true
            docker rm user-auth || true
            docker rmi user-auth:latest || true
            mkdir -p ~/ejoping/deploy/user-auth
            rm -rf ~/ejoping/deploy/user-auth/*
            cp ~/some-path/2joping-user-auth/target/*.jar ~/ejoping/deploy/user-auth/app.jar
            docker run -d \
            --name user-auth \
            --memory="500m" \
            -v ~/ejoping/deploy/user-auth:/app \
            -w /app \
            openjdk:21 \
            java -jar app.jar